# Generated by Django 2.1.4 on 2018-12-20 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_mark_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_to_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment', to='webapp.Comment'),
        ),
    ]
